---
- name: Centos7 basic setup
  hosts: localhost

  vars:
   - python_version: '3.7.3'

  tasks:

  - name: Upgrade packages (except Ansible)
    yum:
      name: '*'
      state: latest
      exclude: ansible
      update_cache: yes
    become: yes

  - name: Install packages
    yum:
      name:
       # Useful packages
       - epel-release
       - wget
       - gcc
       - libcurl
       - yum-cron
       - gzip
       - vim-enhanced
       - htop
       - tree
       - mtr
       - nmap
       - iotop
       - net-tools
       # Packages below are needed for building Python3 from source
       - "@Development tools"
       - libffi-devel
       - zlib-devel
       - bzip2-devel
       - openssl-devel
       - ncurses-devel
       - sqlite-devel
       - readline-devel
       - tk-devel
       - gdbm-devel
       - db4-devel
       - libpcap-devel
       - xz-devel
       - expat-devel
       - postgresql-devel
    become: yes

  - name: Download and untar Python3 source files
    unarchive:
      src: 'https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tar.xz'
      dest: /usr/src
      remote_src: yes
    become: yes

  - name: Configure Python
    command: ./configure --enable-optimizations
    args:
      chdir: '/usr/src/Python-{{ python_version }}'
    become: yes

  - name: Install Python
    make:
      chdir: '/usr/src/Python-{{ python_version }}'
      target: altinstall
    become: yes

  - name: Clean up source files
    file:
      path: '/usr/src/Python-{{ python_version }}'
      state: absent
    become: yes

  - name: Add /usr/local/bin to sudoers path
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^Defaults    secure_path'
      line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
    become: yes

  - name: Check python3 version
    find:
      patterns: '^python3\.[0-9]$'
      paths: /usr/local/bin
      use_regex: yes
    register: python_match

  - set_fact:
      python3_version: '{{ python_match.files[0].path }}'

  - name: Create python3 symlink
    file:
      src: '{{ python3_version }}'
      dest: /usr/local/bin/python3
      state: link
    become: yes

  - name: Check pip3 version
    find:
      patterns: '^pip3\.[0-9]$'
      paths: /usr/local/bin
      use_regex: yes
    register: pip_match

  - set_fact:
      pip3_version: '{{ pip_match.files[0].path }}'

  - name: Create pip3 symlink
    file:
      src: '{{ pip3_version }}'
      dest: /usr/local/bin/pip3
      state: link
    become: yes

  - name: Upgrade pip
    pip:
      name: pip
      executable: pip3
      state: latest
    become: yes

  - name: Install virtualenv
    pip:
      name: virtualenv
      executable: pip3
    become: yes

  - name: Install iPython
    pip:
      name: ipython
      executable: pip3
    become: yes

  - name: Install netmiko
    pip:
      name: netmiko
      executable: pip3
    become: yes

  - name: Install napalm
    pip:
      name: napalm
      executable: pip3
    become: yes

  - name: Clone napaml-ansible
    git:
      repo: https://github.com/napalm-automation/napalm-ansible.git
      dest: ~/napalm-ansible

  - name: Clone ntc-ansible
    git:
      repo: https://github.com/networktocode/ntc-ansible.git
      dest: ~/ntc-ansible

  - name: Install ntc-ansible dependencies
    pip:
      name: ntc-ansible
      executable: pip3
    become: yes

  - name: Clone ntc-templates
    git:
      repo: https://github.com/networktocode/ntc-templates.git
      dest: ~/ntp-templates

  - name: Create ansible-host file
    template:
      src: ansible-hosts.j2
      dest: ~/ansible-hosts

  - name: Create .ansible.cfg file
    template:
      src: ansible-cfg.j2
      dest: ~/.ansible.cfg

  - name: Upgrade Ansible
    yum:
      name: ansible
      state: latest
    become: yes
